# Generated by Django 3.2.12 on 2024-05-20 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fakultas',
            options={'verbose_name_plural': 'Fakultas'},
        ),
        migrations.AlterModelOptions(
            name='peserta',
            options={'verbose_name_plural': 'Data Peserta'},
        ),
        migrations.AlterModelOptions(
            name='prodi',
            options={'verbose_name_plural': 'Prodi'},
        ),
        migrations.RenameField(
            model_name='fakultas',
            old_name='nama',
            new_name='nama_fakultas',
        ),
        migrations.RenameField(
            model_name='prodi',
            old_name='nama',
            new_name='nama_prodi',
        ),
    ]
