# Generated by Django 3.2.12 on 2024-06-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20240520_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='jenis_kelamin',
            field=models.CharField(choices=[('Laki-Laki', 'Laki-Laki'), ('Perempuan', 'Perempuan')], max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='status_mahasiswa',
            field=models.CharField(choices=[('Baru', 'Baru'), ('Lama', 'Lama')], max_length=200, null=True),
        ),
    ]
