# Generated by Django 3.2.12 on 2024-06-27 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_auto_20240607_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='JadwalAbsensi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tanggal', models.DateField()),
                ('checkin', models.TimeField()),
                ('checkout', models.TimeField()),
            ],
        ),
    ]
