# Generated by Django 3.2.12 on 2024-06-27 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_jadwalabsensi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jadwalabsensi',
            options={'verbose_name_plural': 'Jadwal Absensi'},
        ),
    ]
