# Generated by Django 3.2.12 on 2024-06-28 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0005_alter_jadwalabsensi_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jadwalabsensi',
            name='checkin',
        ),
        migrations.RemoveField(
            model_name='jadwalabsensi',
            name='checkout',
        ),
        migrations.AddField(
            model_name='jadwalabsensi',
            name='checkin_mulai',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='jadwalabsensi',
            name='checkin_selesai',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='jadwalabsensi',
            name='checkout_mulai',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='jadwalabsensi',
            name='checkout_selesai',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
