# Generated by Django 3.2.12 on 2024-06-28 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0006_auto_20240628_1446'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jadwalabsensi',
            name='checkin_mulai',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='jadwalabsensi',
            name='checkin_selesai',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='jadwalabsensi',
            name='checkout_mulai',
            field=models.TimeField(default='00:00'),
        ),
        migrations.AlterField(
            model_name='jadwalabsensi',
            name='checkout_selesai',
            field=models.TimeField(default='00:00'),
        ),
    ]
