# Generated by Django 3.2.12 on 2024-07-02 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20240628_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='konfirmasi_password',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='peserta',
            name='password',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
