# Generated by Django 3.2.12 on 2024-07-03 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20240702_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='alamat',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='peserta',
            name='status_mahasiswa',
            field=models.CharField(choices=[('Belum', 'Belum'), ('Sudah', 'Sudah')], max_length=200, null=True),
        ),
    ]
