# Generated by Django 3.2.12 on 2024-07-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20240703_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='peserta',
            name='upload_registrasi',
            field=models.FileField(null=True, upload_to='uploads/'),
        ),
    ]
