# Generated by Django 3.2.12 on 2024-07-03 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_alter_peserta_upload_registrasi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peserta',
            name='upload_registrasi',
            field=models.ImageField(null=True, upload_to='photos/'),
        ),
    ]
