# Generated by Django 3.2.12 on 2024-07-04 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0012_alter_peserta_upload_registrasi'),
    ]

    operations = [
        migrations.AddField(
            model_name='jadwalabsensi',
            name='nama_kegiatan',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
