# Generated by Django 3.2.12 on 2024-07-23 15:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('administrator', '0013_auto_20240711_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='RekapAbsen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_absensi', models.CharField(choices=[('hadir', 'Hadir'), ('izin', 'Izin'), ('tidak_hadir', 'Tidak Hadir')], max_length=100)),
                ('laporan', models.FileField(blank=True, null=True, upload_to='laporan/')),
                ('waktu_absensi', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_mahasiswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('jadwal_absensi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administrator.jadwalabsensi')),
            ],
        ),
    ]
