# Generated by Django 3.2.12 on 2024-07-23 16:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0014_rekapabsen'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rekapabsen',
            options={'verbose_name_plural': 'Rekap Absensi'},
        ),
    ]
