# Generated by Django 3.2.12 on 2024-07-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0015_alter_rekapabsen_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rekapabsen',
            options={'verbose_name_plural': 'RekapAbsensi'},
        ),
        migrations.AddField(
            model_name='rekapabsen',
            name='type_absensi',
            field=models.CharField(choices=[('checkin', 'Checkin'), ('checkout', 'Checkout')], default='checkin', max_length=100),
        ),
    ]
