# Generated by Django 3.2.12 on 2024-08-02 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0017_sertifikat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sertifikat',
            new_name='SertifikatTemplate',
        ),
    ]
